### ISSUE TITLE
New games added 🙏 updates 

### ISSUE THREAD

**Issue by h-ug** [Emperor-One/Hamster-Key-Telegram-Bot#18]

**Comment by Emperor-One** [comment]
I will update. I'm currently not at my computer. I'll merge pull requests, if you send them though.

**Comment by Emperor-One** [comment]
By the way did you get the achievement card 😀

**Comment by h-ug** [comment]
> By the way did you get the achievement card 😀

Yes bro💔😂 but still used  don't have time because exams

**Comment by h-ug** [comment]
> I will update. I'm currently not at my computer. I'll merge pull requests, if you send them though.

I'm waiting for you if have account telegram send me user will chat with you

**Comment by ParsapythonLv** [comment]
> By the way did you get the achievement card 😀

i use a farm bot and fake keys and i don't have that card😂😂
