### ISSUE TITLE
Avoid Bot detection in the future

### ISSUE THREAD

**Issue by joshuazzz1** [Emperor-One/Hamster-Key-Telegram-Bot#3]
Hey developer, I really like this script you have made, but I think that some things that are different for every game are missing, those are required just in case if the hamster kombat devs actually do something to check the keys we claim, so those bot generated keys can match the proper generated keys as much as possible.

https://gist.githubusercontent.com/delasy/96c5340fc5e0617ddc1ff4ddb458d968/raw/c7f66d267f7e4bd995692ac81fabf4f1348b1b05/hamster-kombat-playground-games-promo-keys-generator.js

Please take some references from the script mentioned above and add appropriate `eventType` and `eventId` for each game to generate keys as close as original.

**Comment by Emperor-One** [comment]
You are right. I was working on a separate script for that, but I just couldn't get the api.gamepromo.io requests for the BIKE game. I don't know how this guy did it. I tried to proxy it using burp, but requests to api.gamepromo.io are no where to be found. 

I will add the proper headers and parameters soon, as well as, possibly, proxy support.

**Comment by Emperor-One** [comment]
You can see in the gist too. He also struggled with the BIKE game it seems lol.
line 83
> // todo(delasy): Actually scan BIKE game headers

**Comment by joshuazzz1** [comment]
> You can see in the gist too. He also struggled with the BIKE game it seems lol. line 83
> 
> > // todo(delasy): Actually scan BIKE game headers

Yeah, he couldn't do it, https://gist.github.com/delasy/96c5340fc5e0617ddc1ff4ddb458d968?permalink_comment_id=5157652#gistcomment-5157652

**Comment by Emperor-One** [comment]
I know it's a bit late, but I have made a much stealthier version of the key generator, at least much stealthier than Delasy's script ever will be 😃. It only has games whose data I am sure is accurate, but you can check it out [here](https://github.com/Emperor-One/StealthyHamster), if you'd like.
