### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Abdureshid1** [Emperor-One/Hamster-Key-Telegram-Bot#4]
Response received: {'hasCode': False} 02510b1a-630a-4be8-bee4-9b12ce11ee86
Code is not ready. 31a33344-f236-4835-94b6-0b3556bb749f

**Comment by Emperor-One** [comment]
You just need to wait for it a little bit more! It will get to a point where it says "Code is ready!"

**Comment by Abdureshid1** [comment]
> You just need to wait for it a little bit more! It will get to a point where it says "Code is ready!"

I've already waited 10 minutes, how do I speed up the process?

**Comment by Emperor-One** [comment]
Which game are you generating for? If it is the CLONE game, I think they just changed it recently to where you need to play a lot more to get keys. It used to take 2-3 minutes to get the keys now it takes about 12 minutes for a key. If you really want to, you can decrease the EVENTS_DELAY variable in server.py, but I wouldn't recommend it. You might start hitting their rate limits and erroring out.

**Comment by Abdureshid1** [comment]
> Which game are you generating for? If it is the CLONE game, I think they just changed it recently to where you need to play a lot more to get keys. It used to take 2-3 minutes to get the keys now it takes about 12 minutes for a key. If you really want to, you can decrease the EVENTS_DELAY variable in server.py, but I wouldn't recommend it. You might start hitting their rate limits and erroring out.

All game

**Comment by Abdureshid1** [comment]
> Which game are you generating for? If it is the CLONE game, I think they just changed it recently to where you need to play a lot more to get keys. It used to take 2-3 minutes to get the keys now it takes about 12 minutes for a key. If you really want to, you can decrease the EVENTS_DELAY variable in server.py, but I wouldn't recommend it. You might start hitting their rate limits and erroring out.

Response received: {'error_code': 'TooManyRegister', 'error_message': 'Register event timeout'} a12ce6e4-4301-4a52-8d51-1dc0cb8e7dd1
2024-08-17 23:09:43 | INFO     | 107 - Code is not ready. a12ce6e4-4301-4a52-8d51-1dc0cb8e7dd1
2024-08-17 23:09:43 | INFO     | 89 - Sleeping for 34.25555712157175 seconds.

**Comment by Emperor-One** [comment]
If you used /all it's probably stuck on generating CLONE because, as I said, it takes a bit to generate the CLONE game. It takes about 12 minutes to generate CLONE game keys now. If you were playing the game manually, it would take you almost 30 minutes to generate one key these days.
