### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by sfpghjgf** [Emperor-One/Hamster-Key-Telegram-Bot#7]
How to make the bot send messages separately? Generated and immediately sent. Thank you 😊

**Comment by Emperor-One** [comment]
That's what happens. It generates keys simultaneously (almost) and sends them. If you want them to be sent all at once you can remove the random seconds that are added when the bot sleeps in between register events. 
Go to [line 104](https://github.com/Emperor-One/Hamster-Key-Telegram-Bot/blob/main/server.py#L104) in bot.py
Remove this: ` * (random.uniform(0,0.33) + 1)`

**Comment by sfpghjgf** [comment]
TYSM

**Comment by sfpghjgf** [comment]
![image](https://github.com/user-attachments/assets/e9dff7dd-e63a-42b6-8dfd-c20622e3f097)
No work

**Comment by Emperor-One** [comment]
I don't understand. You want it to be separate messages?

**Comment by sfpghjgf** [comment]
> I don't understand. You want it to be separate messages?

Yes!

**Comment by Emperor-One** [comment]
Delete lines [77 & 78](https://github.com/Emperor-One/Hamster-Key-Telegram-Bot/blob/main/bot.py#L77-L78) in bot.py, and instead add:
```
for key in generated_keys:
        await context.bot.send_message(chat_id=update.effective_chat.id, text=key, parse_mode='MARKDOWNV2')
```

**Comment by sfpghjgf** [comment]
It work
