### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by sfpghjgf** [Emperor-One/Hamster-Key-Telegram-Bot#9]
Why when you generate keys on trim, keys come for cafe? 
![image](https://github.com/user-attachments/assets/17382952-3279-487d-b483-994f5a4d75bd)

**Comment by Emperor-One** [comment]
Pull the latest commit and try again pls

**Comment by sfpghjgf** [comment]
> Pull the latest commit and try again pls

Ok, How can I send a Donat to you?

**Comment by Emperor-One** [comment]
UQAsiMoTSBvhjZ20W3xHx8-U-839KstERKySeR5vzT-QP74S 😄
